---
- firewalld:
    service: https
    permanent: true
    state: enabled
    
- firewalld:
    service: http
    permanent: true
    state: enabled     
  
- service: 
    name: firewalld 
    state: restarted    